files:
  - source: /app/assets/locales/locale-ru.json
    translation: /app/assets/locales/locale-%two_letters_code%.json
  - source: /app/help/en/**/
    translation: /app/help/%two_letters_code%/**/%original_file_name%
